### ISSUE TITLE
Tracing macros part of the API?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Blosc/python-blosc2#102]
The tracing macros are currently part of the API, because they are defined in `blosc2.h`. Yet, they are not used in tests and examples. Should they be part of the API?

**Comment by FrancescAlted** [comment]
Yes, they are part of the API indeed.  They are not used in tests and examples because they need the BLOSC_TRACE envvar to print things out, so a plain `printf` is preferred in these scenarios.
