### ISSUE TITLE
Why NDArray file keep growing when writing

### ISSUE THREAD

**Issue by AlbertRay** [Blosc/python-blosc2#115]
```python
from pathlib import Path
import blosc2
import numpy as np

root = Path("/mnt/disk/test")
path = root / "test.blosc"
if path.exists():
    path.unlink()

shape = (100, 100)
data = blosc2.empty(
    shape,
    urlpath=str(path),
    # cparams={"clevel": 0}
)
print(path.stat().st_size)

np.random.seed(0)
size = 10000
xs = np.random.randint(shape[0], size=size)
ys = np.random.randint(shape[1], size=size)
zs = np.random.randint(10, size=size)
for x, y, z in zip(xs, ys, zs):
    data[x, y] = z
print(path.stat().st_size)
```

the result: file size increases from <1MB to 11MB when writing
I don't think it's a normal situation
```
240
11106499
```

but when clevel=0: always keep same size
```
240
10272
```

![image](https://github.com/Blosc/python-blosc2/assets/20217594/adc0d20a-1551-4cf8-83ab-1cf1401c9de1)

Is my method wrong? Or I can't write NDArray file in this way?

**Comment by FrancescAlted** [comment]
Yes, that is expected.  Whenever there is an update in the array, blosc2 tries to reuse the previous space to store the compressed data, but if it does not fit, it allocates new space in the file. Your use case generates data for every update that cannot be compressed to fit in previous space, so the result is that new space is allocated.

You can workaround this by using `contiguous=False` in the `blosc2.empty` call (BTW, this is the default when using in-memory arrays, so this is not an issue in that case).
