### ISSUE TITLE
second Cmake issue on pi (after issue 142)

### ISSUE THREAD

**Issue by biol75** [Blosc/python-blosc2#143]
I'm not sure where the option is set, but compilation dies here:

cc: error: unrecognized argument in option ‘-mfpu=neon -flax-vector-conversions’
cc: note: valid arguments to ‘-mfpu=’ are: auto crypto-neon-fp-armv8 fp-armv8 fpv4-sp-d16 fpv5-d16 fpv5-sp-d16 neon neon-fp-armv8 neon-fp16 neon-vfpv3 neon-vfpv4 vfp vfp3 vfpv2 vfpv3 vfpv3-d16 vfpv3-d16-fp16 vfpv3-fp16 vfpv3xd vfpv3xd-fp16 vfpv4 vfpv4-d16

starting point:
pi@raspberrypi:~/python-blosc2 $ python setup.py build_ext --inplace

--------------------------------------------------------------------------------
-- Trying 'Ninja' generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is GNU 10.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (1.7s)
-- Generating done (0.0s)
-- Build files have been written to: /home/pi/python-blosc2/_cmake_test_compile/build
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying 'Ninja' generator - success
--------------------------------------------------------------------------------

Configuring Project
  Working directory:
    /home/pi/python-blosc2/_skbuild/linux-armv7l-3.9/cmake-build
  Command:
    /home/pi/venv/lib/python3.9/site-packages/cmake/data/bin/cmake /home/pi/python-blosc2 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/home/pi/venv/lib/python3.9/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/home/pi/python-blosc2/_skbuild/linux-armv7l-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.2 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/pi/venv/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/pi/venv/bin/python -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.9 -DPYTHON_LIBRARY:PATH=/usr/lib/arm-linux-gnueabihf/libpython3.9.so -DPython_EXECUTABLE:PATH=/home/pi/venv/bin/python -DPython_ROOT_DIR:PATH=/home/pi/venv -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/include/python3.9 -DPython3_EXECUTABLE:PATH=/home/pi/venv/bin/python -DPython3_ROOT_DIR:PATH=/home/pi/venv -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.9 -DCMAKE_MAKE_PROGRAM:FILEPATH=/home/pi/venv/lib/python3.9/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release

Not searching for unused variables given on the command line.
CMake Warning (dev) at /home/pi/venv/lib/python3.9/site-packages/skbuild/resources/cmake/FindPythonExtensions.cmake:245 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/pi/venv/lib/python3.9/site-packages/skbuild/resources/cmake/FindPythonExtensions.cmake:252 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

Configuring for Blosc version: 2.10.5
-- Using LZ4 internal sources.
-- Using ZLIB-NG internal sources for ZLIB support.
-- Using CMake version 3.27.7
-- ZLIB_HEADER_VERSION: 1.2.11
-- ZLIBNG_HEADER_VERSION: 2.0.7
-- Arch detected: 'armv6'
-- Basearch of 'armv6' has been detected as: 'arm'
-- ARM floating point arch: -mfloat-abi=hard
-- Architecture-specific source files: arch/arm/armfeature.c;arch/arm/adler32_neon.c;arch/arm/chunkset_neon.c;arch/arm/slide_neon.c
-- Renaming
--     /home/pi/python-blosc2/blosc2/c-blosc2/internal-complibs/zlib-ng-2.0.7/zconf.h
-- to 'zconf.h.included' because this file is included with zlib
-- but CMake generates it automatically in the build directory.
-- The following features have been enabled:

 * CMAKE_BUILD_TYPE, Build type: Release (selected)
 * WITH_GZFILEOP, Compile with support for gzFile related functions
 * ZLIB_COMPAT, Compile with zlib compatible API
 * WITH_OPTIM, Build with optimisation
 * WITH_NEW_STRATEGIES, Use new strategies
 * WITH_UNALIGNED, Support unaligned reads on platforms that support it
 * WITH_ACLE, Build with ACLE
 * WITH_NEON, Build with NEON intrinsics
 * NEON_ADLER32, Support NEON instructions in adler32, using "-mfpu=neon"
 * NEON_SLIDEHASH, Support NEON instructions in slide_hash, using "-mfpu=neon"

-- The following OPTIONAL packages have been found:

 * PythonLibs

-- The following REQUIRED packages have been found:

 * PythonInterp
 * Cython
 * NumPy
 * Threads

-- The following features have been disabled:

 * ZLIB_ENABLE_TESTS, Build test binaries
 * ZLIB_DUAL_LINK, Dual link tests against system zlib
 * WITH_FUZZERS, Build test/fuzz
 * WITH_NATIVE_INSTRUCTIONS, Instruct the compiler to use the full instruction set on this host (gcc/clang -march=native)
 * WITH_MAINTAINER_WARNINGS, Build with project maintainer warnings
 * WITH_CODE_COVERAGE, Enable code coverage reporting
 * WITH_INFLATE_STRICT, Build with strict inflate distance checking
 * WITH_INFLATE_ALLOW_INVALID_DIST, Build with zero fill for inflate invalid distances
 * INSTALL_UTILS, Copy minigzip and minideflate during install

-- The following REQUIRED packages have not been found:

 * PythonExtensions

-- Using ZSTD internal sources.
-- Building for system processor armv7l
-- Building for compiler ID GNU
-- Detected that BLOSC is used a subproject.
-- Disabling support for assembly sources in ZSTD
-- Adding run-time support for NEON
_modinit_prefix:PyInit_
-- Configuring done (2.1s)
-- Generating done (0.1s)
-- Build files have been written to: /home/pi/python-blosc2/_skbuild/linux-armv7l-3.9/cmake-build

lots of warnings suppressed before error is reached

**Comment by biol75** [comment]
I think the 'NEON' test is not right on the pi. 

Setting COMPILER_SUPPORT_NEON FALSE throughout blosc2/c-blosc2/CMakeLists.txt allows compilation to proceed and generated a set of .so files

**Comment by FrancescAlted** [comment]
Thanks for bringing this to our attention.  Please see my comment at: https://github.com/piwheels/packages/issues/401

**Comment by FrancescAlted** [comment]
Fixed in latest C-Blosc2 2.11.2 version.
