### ISSUE TITLE
Feature Request: Support b2nd_from_cframe() and b2nd_to_cframe() in the python api.

### ISSUE THREAD

**Issue by angshine** [Blosc/python-blosc2#146]
Hi, thank you for the excellent work!

As mentioned in #114, it would be fantastic to have support for converting between NDArray and c2frame in the Python API. I noticed that this is already supported in c-blosc2 with the functions `b2nd_from_cframe()` and `b2nd_to_cframe()`.

**Comment by FrancescAlted** [comment]
Hi.  Sure, this would be a good thing to implement, and pretty easy to do.  Would you mind providing a PR?

**Comment by FrancescAlted** [comment]
Implemented in #147
