### ISSUE TITLE
Python-blosc2 should be linked to system-installed blocsc2 shared library by default

### ISSUE THREAD

**Issue by KOLANICH** [Blosc/python-blosc2#15]

**Comment by mgorny** [comment]
Could you please reconsider? Vendoring packages is true hell for Linux distributions which now have to maintain two copies of the same library, and effectively became a blocker for blosc2 in Gentoo.

**Comment by mgorny** [comment]
(just as an option, the default doesn't matter to us)

**Comment by ArchangeGabriel** [comment]
I’m seconding this.

**Comment by ArchangeGabriel** [comment]
I have an almost working patch for this at https://github.com/Blosc/python-blosc2/commit/a1e419ddc9773ab6cc80c397e39935e9b6b76ded, but it needs a fix for shared linking apparently.

**Comment by FrancescAlted** [comment]
Thanks for looking into this @ArchangeGabriel .  I have spent some time trying to make this work, but no success so far.  FWIW, we should try to include blosc2.h for the Python extension too.

**Comment by bnavigator** [comment]
@ArchangeGabriel are you aware that [PyTables also does something very nasty](https://github.com/PyTables/PyTables/blob/e34d1f78ed905694672c49a33ef3004a2f8899f2/setup.py#L111]) with assuming the "bundled" c-blosc2 is available?
