### ISSUE TITLE
set_slice() fails when the blosc array is of different dtype

### ISSUE THREAD

**Issue by tnorth** [Blosc/python-blosc2#168]
Hi Blosc team,

I'm experimenting with blosc2 ndarray and I've noticed that the following fails: (using blosc 2.5.1)

```python
N = 1024 # or whatever
fp = blosc2.empty((N,N), chunks=(N//8, N//8), blocks=(8, 8), dtype=np.complex128)
a = np.zeros(N)
fp[:,0] = a

```
`
blosc2/ndarray.py:163, in NDArray.__setitem__(self, key, value)
    160 elif isinstance(value, NDArray):
    161     value = value[...]
--> 163 return super().set_slice(key, value)
File blosc2_ext.pyx:2109, in blosc2.blosc2_ext.NDArray.set_slice()
File blosc2_ext.pyx:1911, in blosc2.blosc2_ext._check_rc()
RuntimeError: Error while setting the slice
`

However, the assignation is sucessful if `a = np.zeros(N, dtype=np.complex128)`.

It can also be noted that assigning a complex64 to a float32 blosc array silently copies half of the source array to the blosc array:
```python
fp = blosc2.empty((N,N), chunks=(N//8, N//8), blocks=(8, 8), dtype=np.float32)
a = np.zeros(N, dtype=np.complex64)
a[:] = 1 + 2j
fp[:,0] = a
fp[:,0]
 array([1., 2., 1., ..., 2., 1., 2.], dtype=float32)
```

So it seems that no check for dtype matching is made, and if the size of the target array (in bytes) is larger than the blosc array, the copy will consider take as many bytes as it needs to be full. If the dtype of the source array (`a`) is smaller than the one of the blosc array, a slice error occurs.

Anything that I missed here? Am I misusing blosc2.empty?

**Comment by FrancescAlted** [comment]
No, this was a lack of dtype checking.  I have 'fixed' this by raising a `ValueError` in 2066abb.  I am not sure on whether blosc2 should go ahead and convert numpy arrays on-the-flight internally or, provided that blosc2 is geared towards large datasets, probably doing this conversion under the hood is not a good idea (can lead to large memory usage quite easily).  What do you think?

**Comment by tnorth** [comment]
Thanks for the quick feedback! I think you're right, converting on the fly would be expensive. This fix (I'll test it), or emitting a warning on incompatible dtype sound like a good solution, thanks!

**Comment by FrancescAlted** [comment]
Cool.  Closing then.
