### ISSUE TITLE
Generate arm64 Mac wheels

### ISSUE THREAD

**Issue by oscargm98** [Blosc/python-blosc2#19]
In https://github.com/Blosc/python-blosc2/pull/14, when specifying "CIBW_ARCHS_MACOS: x86_64 arm64", the arm64 build creates a wheel with the same filename as the previously built x86_64 one. This error occurs because scikit-build doesn't natively support Apple Silicon yet.
However, it seems it will not take too much time for them to implement this, so when this happens we have to add some code to python-blosc2/.github/workflows/cibuildwheels.yml. In line 94 add:

          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_TEST_SKIP: '*_arm64'

**Comment by FrancescAlted** [comment]
Fixed long time ago.
