### ISSUE TITLE
Optimize LazyUDF evaluation when using postfilters or pre filters

### ISSUE THREAD

**Issue by martaiborra** [Blosc/python-blosc2#193]
The `blosc2.NDArray.__getitem__` method uses ndindex, which consumes a lot of time. This `__getitem__` is used for each block and each blosc2.NDArray operand in a LazyUDF computed with prefilters or postfiters. It would be interesting to optimize the `aux_udf` function by calling the `b2nd_get_slice_cbuffer` C function instead of the `__getitem__` method.

**Comment by FrancescAlted** [comment]
This has been optimized out during the past weeks.  Closing.
