### ISSUE TITLE
blosc2 slicing 

### ISSUE THREAD

**Issue by orena1** [Blosc/python-blosc2#194]
Hi, maybe I do not understand exactly how slicing should work on a blosc2 file, but I assumed it will be the same as numpy, I think this example shows the problem
```python
In [25]: np.zeros(shape=(614, 4, 360, 640))[:,:,::4].shape
Out[25]: (614, 4, 90, 640)

In [26]: tm = blosc2.open(urlpath=b2nd_path, mode="r")

In [27]: tm.shape
Out[27]: (614, 4, 360, 640)

In [28]: tm[:,:,::4].shape
Out[28]: (614, 4, 357, 640)

```

Am I mistaken that one can just load slices of the file? thanks

**Comment by FrancescAlted** [comment]
Yes, unfortunately, `step` is [not properly supported yet](https://www.blosc.org/python-blosc2/reference/autofiles/ndarray/blosc2.NDArray.__getitem__.html#blosc2.NDArray.__getitem__).  Although our goal is supporting it, the possibility of retrieving NumPy arrays larger than memory makes the implementation tricky. Indeed, raising an error would have been better than just documenting it.

**Comment by FrancescAlted** [comment]
Starting from the new release, an [error will be raised](https://github.com/Blosc/python-blosc2/commit/4bc0a0d11bb55740f051a1b6de3cc935b4384023) .

**Comment by FrancescAlted** [comment]
It turned out that this was not that difficult to support for the `__getitem__()`: https://github.com/Blosc/python-blosc2/commit/8cd8acdc511cf69cd386efe37e0bce4fc07e4fff

The support for steps is still missing for other scenarios though.

**Comment by FrancescAlted** [comment]
We are supporting steps for reading scenarios in main, while supporting that for writing is going to be way more difficult (if we ever do it).  So closing.
