### ISSUE TITLE
Possible bug in `blosc_decompress`

### ISSUE THREAD

**Issue by martaiborra** [Blosc/python-blosc2#2]
If an empty bytearray is compressed and then decompressed `header->blocksize <= 0 || header->blocksize > header->nbytes`,
which launches an error in `blosc_read_header`. 
This is seen in the `test_bytes_array.py`.

**Comment by FrancescAlted** [comment]
Is this active or it has been fixed already?

**Comment by martaiborra** [comment]
Ups, it has been fixed.
