### ISSUE TITLE
Migration to `scikit-build-core`

### ISSUE THREAD

**Issue by LecrisUT** [Blosc/python-blosc2#223]
It is recommended that projects migrate from `scikit-build` to `scikit-build-core` when possible. Most development is focused there and it is a very CMake friendly and pythonic build system. For now I only wanted to create an issue to get your opinion on this and track the progress of such migration. If you have questions or need help, feel free to ask.

**Comment by FrancescAlted** [comment]
That sounds good to me.  Would you like to provide a PR?

**Comment by LecrisUT** [comment]
`Cython` functionality is a bit [more convoluted](https://scikit-build-core.readthedocs.io/en/latest/getting_started.html#cmake-file), but this CMake project doesn't look too difficult to port. It would take me some time to setup the environment and find the time. Happy to help contribute in a PR, it would just be a bit slow and would need a few reminders if it's ok. Always available to review and share references though.

**Comment by FrancescAlted** [comment]
Now that 3.0.0-beta.3 is out, this can be closed.
