### ISSUE TITLE
All branches in the conditional structure have same implementation

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Blosc/python-blosc2#232]
After https://github.com/Blosc/python-blosc2/commit/587d37b61403d07fa62cbac62c629776ffec3ed7, the following code doesn't look good:
https://github.com/Blosc/python-blosc2/blob/57acd81f7a93dd0044384ce2bfdddc3021c6ffce/blosc2/lazyexpr.py#L589-L593

Remove the `if`/`else`?

**Comment by FrancescAlted** [comment]
Good catch.  Fixed in https://github.com/Blosc/python-blosc2/commit/b3b6717ad8f4fe3d17beef0949feda3b9ab9e53f
