### ISSUE TITLE
F841 Local variable `any_persisted` is assigned to but never used

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Blosc/python-blosc2#238]
It looks like the ruff linter has discovered a real issue:
https://github.com/Blosc/python-blosc2/blob/99525d3141ac802e60b3d7bea4dabd1f2ae92b8f/blosc2/lazyexpr.py#L891-L895

At the very least the comment `iter_disk = all_ndarray and any_persisted` is misleading:
https://github.com/Blosc/python-blosc2/blob/99525d3141ac802e60b3d7bea4dabd1f2ae92b8f/blosc2/lazyexpr.py#L896-L899

**Comment by FrancescAlted** [comment]
Thanks @DimitriPapadopoulos .  I was playing with this lately, and I fixed the unused var just now.
