### ISSUE TITLE
Problems when building wheels for Windows x86

### ISSUE THREAD

**Issue by martaiborra** [Blosc/python-blosc2#28]
When trying to build wheels for Windows x86 it doesn't pass the tests.
At first, the following tests failed:
- `test_python_blosc` in `test_pack_array_exceptions`, with a `Memory Error` instead of a `Value Error`.
- `test_schunk_insert` with a `RunTimeError`when decompressing or appending a chunk.
- `test_schunk_update` with `numpy.core.__exceptions.__ArrayMemoryError` when creating the numpy buffer to append it later as a chunk in the `test_schunk_update_numpy`. And with a `RunTimeError` when appending the `bytes_obj`.
- `test_vlmeta` with `numpy.core.__exceptions.__ArrayMemoryError` when creating the numpy buffer to append it later as a chunk. 
Then, we tried running only the `test_schunk_insert`, which failed again when inserting or appending the chunk with a `RunTimeError` or when creating the numpy array to be appended with a `numpy.core.__exceptions.__ArrayMemoryError` .

After that, we tried to modify the c-blosc2 submodule by avoiding the realloc function when appending, inserting and updating a chunk, and when adding or updating a vlmeta with the following changes in the code:

- In `schunk_append_buffer `: 
`  int nchunks = blosc2_schunk_append_chunk(schunk, chunk, true);
  free(chunk);`
- In `schunk_insert_chunk`: 
`  //if (copy) {
    // Make a copy of the chunk
    uint8_t *chunk_copy = malloc(chunk_cbytes);
    memcpy(chunk_copy, chunk, chunk_cbytes);
    chunk = chunk_copy;
  //}`
- In `schunk_update_chunk`: 
`  //if (copy) {
    // Make a copy of the chunk
    uint8_t *chunk_copy = malloc(chunk_cbytes);
    memcpy(chunk_copy, chunk, chunk_cbytes);
    chunk = chunk_copy;
  //}`
- In `blosc2_vlmeta_add`: 
`  uint8_t *vlmetalayer_content = malloc(csize);
  memcpy(vlmetalayer_content, content_buf, csize);
  vlmetalayer->content = vlmetalayer_content;
  vlmetalayer->content_len = csize;
  schunk->vlmetalayers[schunk->nvlmetalayers] = vlmetalayer;
  schunk->nvlmetalayers += 1;`
- In `blosc2_vlmeta_update`: 
`  uint8_t *vlmetalayer_content = malloc(csize);
  memcpy(vlmetalayer_content, content_buf, csize);
  vlmetalayer->content = vlmetalayer_content;
  vlmetalayer->content_len = csize;`
After that, nothing seemed to change,  so it might be due to a memory limitation of Windows x86.

**Comment by FrancescAlted** [comment]
There are no plans to support any 32 bit platform. Closing.
