### ISSUE TITLE
Support back a type size that is not a divisor of the buffer size and restore pack function

### ISSUE THREAD

**Issue by martaiborra** [Blosc/python-blosc2#29]
Since it has been restored the support for a type size that is not a divisor of the buffer size  according to (https://github.com/Blosc/c-blosc2/issues/356) python-blosc2 could also support that and change back to the previous pack() function. In this previous version we were not forced to set `typesize=1` obtaining better compression results.

**Comment by FrancescAlted** [comment]
This has been fixed in PR #30
