### ISSUE TITLE
test dependencies

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Blosc/python-blosc2#316]
Shouldn't these two blocks be in sync?

https://github.com/Blosc/python-blosc2/blob/9021ad5a854a623fbd909b6bfcec2915c2183769/pyproject.toml#L46-L50

https://github.com/Blosc/python-blosc2/blob/9021ad5a854a623fbd909b6bfcec2915c2183769/pyproject.toml#L70

Is one of them redundant?

**Comment by FrancescAlted** [comment]
I don't remember well, but I think the idea was to avoid using torch when testing wheels, specially on aarch64 which is pretty slow (emulated).  I'll add a note for the future.
