### ISSUE TITLE
blosc2.compress2 does not release internal memory

### ISSUE THREAD

**Issue by biblicabeebli** [Blosc/python-blosc2#32]
I am in the process of comparing different compression options on some bulk data, and I have been unable to complete tests with blosc2.compress2 because it quickly accumulates memory.  I have run identical or near-identical code using the zstd library and the lz4 library without these issues.

Every call to blosc2.compress2 retains some amount of memory.  This is present on all compression codecs, but is particularly extreme on zstd, where it amounts to significantly _more_ than the sum of the read-in data and the compressed output data.  It also occurs regardless of compression level, shuffle mode, typesize, blocksize, nthreads,  use_dict, splitmode... though I don't have full coverage, that's a lot of permutations and I was testing within ranges that produced best-for-me output.

The only call to blosc2 in my code is the following.  The test was to read in about a gigabyte of data across many different files (so there were many separate calls to compress2) and run it through permutations of options to find an optimal combination of parameters.  I have also tried inserting calls to `gc.collect()` but this had no effect.

```
value = len(
            blosc2.compress2(
                content, clevel=comp_level, shuffle=shuffle, compcode=MODE,
                typesize=typesize, nthreads=1, block_size=block_size,
                use_dict=use_dict,
                splitmode=blosc2.NEVER_SPLIT,
            )
        )
blosc2.free_resources()  # this has no apparent effect.
```

Platform is Ubuntu 21.10
I have tested this on python 3.7.12 and 3.8.8.

**Comment by biblicabeebli** [comment]
(Did not test meta parameters)

**Comment by FrancescAlted** [comment]
Sorry, that felt into the cracks.  We have updated the C library to latest version.  Could you confirm that the leak is still there?  Thanks!

**Comment by biblicabeebli** [comment]
I will try and get to this and report back. Its been a while but I still have my test code... somewhere...

**Comment by FrancescAlted** [comment]
Ping?

**Comment by biblicabeebli** [comment]
While I haven't gotten back to this it is still pinned in my inbox and I will try to get to it.

**Comment by biblicabeebli** [comment]
I am no longer able to get memory leak or any crashes to occur once I reviewed my benchmarking code.  I was able to complete developing that benchmarking code without issue.

The core issue may have been providing a meta parameter value between 128 and 256, which now causes a crash (invalid integer type somewhere is the c code).

I have observed that decode speed for blosc's zstd implementation is roughly halved when any block size other than 0 is provided. This may be a bug or a fundamental design constraint of the parameter, I leave that data point in your hands, you may close this issue at your leisure.

**Comment by biblicabeebli** [comment]
This popped up on my feed, this issue is long-since closed.
