### ISSUE TITLE
Please provide sdist for blosc2 3.0.0 on PyPI

### ISSUE THREAD

**Issue by sunpoet** [Blosc/python-blosc2#351]
**Describe the bug**
sdist for blosc2 3.0.0 is missing on PyPI.

**To Reproduce**
Check https://pypi.org/project/blosc2/#files and see
```
Source Distributions
No source distribution files available for this release
```

**Expected behavior**
sdist is available on PyPI just like previous releases, e.g. 2.7.1.

**Comment by FrancescAlted** [comment]
Fixed.  I am trying to fix this long term in https://github.com/Blosc/python-blosc2/pull/353

**Comment by sunpoet** [comment]
Thanks!
