### ISSUE TITLE
aarch64 wheels not published for 0.3.1 and newer

### ISSUE THREAD

**Issue by AWSjswinney** [Blosc/python-blosc2#48]
Blosc2 published aarch64 wheels for prior to version 0.3.1, but starting on that version, aarch64 wheels were ommited from publication on pypi.org.

I noticed 33b04cd21155a389333d3dbd6b73f698a65529de and 27084c97dea3e1cdf65fdfe7bc7e4d4e37c11955 both refer to problems with the build crashing on aarch64 for python 3.8, but I haven't found any more information about this.

Can wheels be published again for current and future versions for aarch64?

**Comment by FrancescAlted** [comment]
Yeah, we've had issues on this. More info here:
https://github.com/Blosc/python-blosc2/blob/main/.github/workflows/cibuildwheels.yml#L22

**Comment by FrancescAlted** [comment]
This has been fixed long ago.
